import { DataSource } from 'typeorm';
import { Dine } from '../../entities/dine.entity';
import { Floor } from '../../entities/floor.entity';

export async function seedDine(
  dataSource: DataSource,
  floorsMap: Record<string, Floor>,
): Promise<void> {
  const dineRepository = dataSource.getRepository(Dine);

  const sampleDine: Partial<Dine>[] = [{
    slug: 'cheezious',
    name: 'Cheezious',
    description:
      'Delicious cheesy delights and comfort food favorites. Experience the perfect blend of flavors in every bite.',
    logo: '/logo/cheezious logo.jpg',
    backgroundImage: '/dine/cheezious.jpeg',
    category: 'Fast Food',
    contact: {
      phone: '+971-50-501-8599',
    },
    floor: floorsMap['Ground'],
    floorId: floorsMap['Ground']?.id,
    mapPosition: { x: 25, y: 40 },
  },
  {
    slug: 'pizzahut',
    name: 'Pizza Hut',
    description: 'World-famous pizza with fresh ingredients and signature flavors. Dine in, carry out, or enjoy delivery.',
    logo: '/logo/pizza hut logo.jpg',
    backgroundImage: '/dine/pizzahut.jpeg',
    category: 'Restaurant',
    contact: { phone: '+971-50-501-8598' },
    floor: floorsMap['First Floor'],
    floorId: floorsMap['First Floor']?.id,
    mapPosition: { x: 30, y: 45 },
  },
  {
    slug: 'wild-wings',
    name: 'Wild Wings',
    description: 'Bold flavors and crispy wings in a vibrant atmosphere. Perfect for sharing with friends and family.',
    logo: '/logo/wings logo.jpg',
    backgroundImage: '/dine/wild-wings.jpeg',
    category: 'Restaurant',
    contact: { phone: '+971-50-501-8597' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 35, y: 50 },
  },
  {
    slug: 'mcdonalds',
    name: "McDonald's",
    description: "I'm lovin' it! Enjoy your favorite burgers, fries, and more. Fast, friendly service in a clean, comfortable environment.",
    logo: '/logo/Macdonalds logo.jpg',
    backgroundImage: '/dine/macdonalds.jpeg',
    category: 'Fast Food',
    contact: { phone: '+971-50-501-8516' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 39, y: 63 },
  },
  {
    slug: 'hardees',
    name: "Hardee's",
    description: "Made from scratch. Fresh, quality ingredients in every burger, sandwich, and breakfast item. Bold flavors you'll love.",
    logo: '/logo/hardees logo.jpg',
    backgroundImage: '/dine/hardees.jpeg',
    category: 'Fast Food',
    contact: { phone: '+971-50-501-8523' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 40, y: 64 },
  },
  {
    slug: 'redapple',
    name: 'Red Apple',
    description: 'A delightful dining experience offering fresh and flavorful dishes in a welcoming atmosphere.',
    logo: '/logo/red apple logo.jpg',
    backgroundImage: '/dine/redapple.JPG',
    category: 'Restaurant',
    contact: { phone: '+971-50-501-8524' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 38, y: 55 },
  },
  {
    slug: 'optp',
    name: 'OPTP',
    description: 'Experience authentic flavors and traditional cuisine in a modern setting.',
    logo: '/logo/optp logo.jpg',
    backgroundImage: '/dine/optp.JPG',
    category: 'Restaurant',
    contact: { phone: '+971-50-501-8525' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 42, y: 52 },
  },
  {
    slug: 'chachajee',
    name: 'Chachajee',
    description: 'A beloved local favorite serving delicious traditional dishes with a modern twist.',
    logo: '/logo/chachajee logo.jpg',
    backgroundImage: '/dine/chachajee.JPG',
    category: 'Restaurant',
    contact: { phone: '+971-50-501-8526' },
    floor: floorsMap['First Floor'],
    floorId: floorsMap['First Floor']?.id,
    mapPosition: { x: 44, y: 48 },
  },
  {
    slug: 'cinnabon',
    name: 'Cinnabon',
    description: 'A bakery and dessert store specializing in warm, gooey cinnamon rolls, pastries, and sweet treats. Indulge in freshly baked goods and delicious desserts.',
    logo: '/logo/cionnabon.jpg',
    backgroundImage: '/dine/cinnabon web.JPG',
    category: 'Desserts & Beverages',
    contact: { phone: '+971-50-501-8610' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 75, y: 45 },
  },
  {
    slug: 'simplysufi',
    name: 'Simply Sufi',
    description: 'Authentic flavors and traditional recipes served in a warm and inviting atmosphere.',
    logo: '/logo/simplysufi logo.jpg',
    backgroundImage: '/dine/simplysufi.JPG',
    category: 'Restaurant',
    contact: { phone: '+971-50-501-8527' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 36, y: 57 },
  },
  {
    slug: 'rewayat',
    name: 'Rewayat',
    description: 'Traditional cuisine with a contemporary touch, bringing heritage flavors to your table.',
    logo: '/logo/rewayat logo.jpg',
    backgroundImage: '/dine/rewayat.JPG',
    category: 'Restaurant',
    contact: { phone: '+971-50-501-8528' },
    floor: floorsMap['First Floor'],
    floorId: floorsMap['First Floor']?.id,
    mapPosition: { x: 40, y: 44 },
  },
  {
    slug: 'spicefactory',
    name: 'Spice Factory',
    description: 'Bold flavors and aromatic spices come together to create an unforgettable dining experience.',
    logo: '/logo/spice factory logo.jpg',
    backgroundImage: '/dine/spicefactory.JPG',
    category: 'Restaurant',
    contact: { phone: '+971-50-501-8529' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 41, y: 56 },
  },
  {
    slug: 'chinagrill',
    name: 'China Grill',
    description: 'Authentic Chinese cuisine with grilled specialties and traditional favorites.',
    logo: '/logo/china grill logo.jpg',
    backgroundImage: '/dine/chinagrill.JPG',
    category: 'Restaurant',
    contact: { phone: '+971-50-501-8530' },
    floor: floorsMap['First Floor'],
    floorId: floorsMap['First Floor']?.id,
    mapPosition: { x: 43, y: 51 },
  },
  {
    slug: 'kababjees',
    name: 'Kababjees',
    description: 'Premium kebabs and grilled specialties made with the finest ingredients and traditional techniques.',
    logo: '/logo/kabab jees logo.jpg',
    backgroundImage: '/dine/kababjees.JPG',
    category: 'Restaurant',
    contact: { phone: '+971-50-501-8531' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 39, y: 54 },
  },
  {
    slug: 'coffee-planet',
    name: 'Coffee Planet',
    description: 'All you need is coffee, WiFi & dreams. Experience premium coffee blends and a cozy atmosphere perfect for work or relaxation.',
    logo: '/logo/CoffeePlanetLogo.png',
    backgroundImage: '/dine/coffeeplanet web.JPG',
    category: 'Cafe',
    contact: { phone: '+971-50-501-8532' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 45, y: 60 },
  },
  {
    slug: 'corn-station',
    name: 'Corn Station',
    description: 'Enjoy delicious sweet corn, refreshing slush drinks, and freshly popped popcorn. A perfect quick snack stop for the whole family.',
    logo: '/logo/corn station.jpg',
    backgroundImage: '/dine/corn station web.JPG',
    category: 'Snacks',
    contact: { phone: '+971-50-501-8533' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 47, y: 62 },
  },
  {
    slug: 'asian-fusion',
    name: 'Asian Fusion',
    description: 'Experience authentic Asian cuisine with a modern twist. Enjoy fresh juice and shake options alongside traditional dishes in a contemporary setting.',
    logo: '/logo/asian fusion.jpg',
    backgroundImage: '/dine/asian fusion web.JPG',
    category: 'Restaurant',
    contact: { phone: '+971-50-501-8534' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 49, y: 64 },
  },
  {
    slug: 'eklairs',
    name: 'Eklairs',
    description: 'Indulge in premium eclairs and artisanal pastries. From classic flavors to innovative creations, experience the perfect blend of sweetness and elegance in every bite.',
    logo: '',
    backgroundImage: '/dine/eklairs web.JPG',
    category: 'Desserts',
    contact: { phone: '+971-50-501-8535' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 51, y: 66 },
  },
  {
    slug: 'frutastic',
    name: 'Frutastic',
    description: 'Fresh, natural juices made from the finest fruits. Enjoy a variety of healthy options including orange, apple, sugarcane, and more. Refreshing and nutritious beverages for every taste.',
    logo: '/logo/FrustasticLogo.png',
    backgroundImage: '/dine/frutastic web.JPG',
    category: 'Juice Bar',
    contact: { phone: '+971-50-501-8536' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 53, y: 68 },
  },
  {
    slug: 'gloria-jeans-coffees',
    name: 'Gloria Jean\'s Coffees',
    description: 'Established in 1979, Gloria Jean\'s Coffees offers premium coffee blends, chillers, and delicious pastries. Experience the perfect cup of coffee in a welcoming atmosphere.',
    logo: '',
    backgroundImage: '/dine/gloria web.JPG',
    category: 'Cafe',
    contact: { phone: '+971-50-501-8537' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 55, y: 70 },
  },
  {
    slug: 'goshez',
    name: 'Goshez',
    description: 'Ice cream solves everything! Indulge in premium ice cream, frozen treats, and delightful desserts. From classic flavors to innovative creations, satisfy your sweet cravings.',
    logo: '/logo/coshes.jpg',
    backgroundImage: '/dine/goshez web.JPG',
    category: 'Ice Cream',
    contact: { phone: '+971-50-501-8538' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 57, y: 72 },
  },
  {
    slug: 'juice-fruity',
    name: 'Juice Fruity',
    description: 'Fresh, natural juices made from the finest fruits. Enjoy a variety of healthy options including orange, apple, sugarcane, and more. Refreshing and nutritious beverages for every taste.',
    logo: '/logo/juice fruity.jpg',
    backgroundImage: '/dine/juice fruity web.JPG',
    category: 'Juice Bar',
    contact: { phone: '+971-50-501-8540' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 61, y: 76 },
  },
  {
    slug: 'juice-station',
    name: 'Juice Station',
    description: 'As natural as you! Fresh, pure juices made from the finest fruits with no additives. Grab & go options available in 250ML, 500ML, and 1LTR sizes. Experience the authentic taste of natural ingredients.',
    logo: '/logo/juice station.jpg',
    backgroundImage: '/dine/juice station web.JPG',
    category: 'Juice Bar',
    contact: { phone: '+971-50-501-8541' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 63, y: 78 },
  },
  {
    slug: 'king-coffee',
    name: 'King Coffee',
    description: 'The Master of Coffee. Experience premium coffee blends, Chinese cuisine, burgers, and more in a warm and welcoming atmosphere. Perfect for coffee lovers and food enthusiasts.',
    logo: '/logo/king coffe.jpg',
    backgroundImage: '/dine/king coffee web.JPG',
    category: 'Cafe',
    contact: { phone: '+971-50-501-8542' },
    floor: floorsMap['First Floor'],
    floorId: floorsMap['First Floor']?.id,
    mapPosition: { x: 65, y: 80 },
  },
  {
    slug: 'king-corn',
    name: 'King Corn',
    description: 'Sweet & Tasty! Enjoy delicious sweet corn, popcorn, ice cream, and refreshing slush drinks. A perfect snack destination offering a variety of flavors and treats for everyone.',
    logo: '/logo/king corn.jpg',
    backgroundImage: '/dine/king corn web.JPG',
    category: 'Snacks',
    contact: { phone: '+971-50-501-8543' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 67, y: 82 },
  },
  {
    slug: 'pop-nosh',
    name: 'Pop Nosh',
    description: 'Gourmet Popcorn! Indulge in a variety of premium popcorn flavors including chocolate, caramel, cheese, and colorful candy-coated options. Perfect for movie nights and sweet cravings.',
    logo: '/logo/pop nosh.jpg',
    backgroundImage: '/dine/popnosh web.JPG',
    category: 'Snacks',
    contact: { phone: '+971-50-501-8544' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 69, y: 84 },
  },
  {
    slug: 'sweet-salt',
    name: 'Sweet & Salt',
    description: 'Always Fresh! Enjoy authentic chaat items including Raj Kachori, Gol Gappay, Dahi Bhally, Chana Chaat, Papri Chaat, and Samosa Chaat. Also offering a variety of teas including Pink Tea and Green Tea.',
    logo: '/logo/sweet and salt.jpg',
    backgroundImage: '/dine/sweet&salt web.JPG',
    category: 'Snacks',
    contact: { phone: '+971-50-501-8545' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 71, y: 86 },
  },
  {
    slug: 'tim-hortons',
    name: 'Tim Hortons',
    description: 'Always Fresh Since 1964. Crafted with care, made to order. Enjoy premium coffee, fresh donuts, pastries, and baked goods in a warm and welcoming cafe atmosphere.',
    logo: '/logo/tim hrtons.jpg',
    backgroundImage: '/dine/tim horton web.JPG',
    category: 'Cafe',
    contact: { phone: '+971-50-501-8546' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 73, y: 88 },
  },
  {
    slug: 'islamic-honey-centre',
    name: 'Islamic Honey Centre',
    description: 'Discover the finest quality honey products. From pure natural honey to specialty varieties, experience the authentic taste and health benefits of premium honey.',
    logo: '/logo/islamicHoneyCenterlogo.png',
    backgroundImage: '/dine/islamic honey web.JPG',
    category: 'Specialty Store',
    contact: { phone: '+971-50-501-8539' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 59, y: 74 },
  },
  {
    slug: 'baskin-robbins',
    name: 'Baskin Robbins',
    description: 'Ice Cream & Cakes! Indulge in a wide variety of premium ice cream flavors, sundaes, and delicious ice cream cakes. Experience the joy of 31 flavors and more in a vibrant, welcoming atmosphere.',
    logo: '/logo/BR BASKIN.jpg',
    backgroundImage: '/dine/baskin robin web.JPG',
    category: 'Ice Cream',
    contact: { phone: '+971-50-501-8547' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 75, y: 90 },
  },
  {
    slug: 'ashraf-naturals',
    name: 'Ashraf Naturals',
    description: 'Discover premium natural products including pure honey, organic foods, and health essentials. Experience the finest quality natural goods in a welcoming and comfortable environment.',
    logo: '/logo/ASHRAF.jpg',
    backgroundImage: '/dine/ashraf naturals web.JPG',
    category: 'Specialty Store',
    contact: { phone: '+971-50-501-8548' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 77, y: 92 },
  },
  {
    slug: 'dark-side',
    name: 'Dark Side',
    description: 'Indulge in delicious ice cream, refreshing slush drinks, premium coffee, and specialty shakes. A perfect destination for sweet treats and cool beverages.',
    logo: '/logo/DarkSideLogo.png',
    backgroundImage: '/dine/dark side web.JPG',
    category: 'Desserts & Beverages',
    contact: { phone: '+971-50-501-8535' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 78, y: 93 },
  },
  {
    slug: 'cigarettes-chocolates',
    name: 'Cigarettes & Chocolates',
    description: 'Your one-stop shop for premium chocolates, candies, confectionery, and tobacco products. Discover a wide selection of sweet treats and convenience items.',
    logo: '/logo/Cigarettes&ChocolatesLogo.png',
    backgroundImage: '/dine/ciggeretes and choclates web.JPG',
    category: 'Convenience Store',
    contact: { phone: '+971-50-501-8536' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 79, y: 94 },
  },
  {
    slug: 'house-of-mandi',
    name: 'House of Mandi',
    description: 'Experience the real Arabic taste with authentic Mandi dishes. Specializing in traditional Arabic cuisine including chicken and mutton Mandi, BBQ platters, appetizers, and desserts in a warm, culturally themed setting.',
    logo: '/logo/HouseofMandiLogo.png',
    backgroundImage: '/dine/house of mandi web.JPG',
    category: 'Restaurant',
    contact: { phone: '+971-50-501-8537' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 80, y: 95 },
  },
  {
    slug: 'howdy',
    name: 'Howdy',
    description: 'Wild vibes and bold flavors! A Western-themed fast-food restaurant offering delicious burgers, prawn specialties, combo deals, and classic favorites. Experience the sea-sational twist with our signature Prawn Star burger and enjoy fantastic deals for individuals, couples, and groups.',
    logo: '/logo/HowdyLogo.png',
    backgroundImage: '/dine/howdy web.JPG',
    category: 'Fast Food',
    contact: { phone: '+971-50-501-8538' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 81, y: 96 },
  },
  {
    slug: 'ice-curl',
    name: 'Ice Curl',
    description: 'Taste the original! A dessert kiosk specializing in rolled ice cream, customizable frozen treats, and refreshing beverages. Enjoy signature flavors like Rooh Afza Lemonade, Espresso Lite, Fudge Brownie, All About Oreo, and Lemonicious.',
    logo: '/logo/IceCurlLogo.png',
    backgroundImage: '/dine/ice curl web.JPG',
    category: 'Desserts & Beverages',
    contact: { phone: '+971-50-501-8539' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 82, y: 97 },
  },
  {
    slug: 'jelly-factory',
    name: 'Jelly Factory',
    description: 'A vibrant candy and ice cream cart offering a wide selection of colorful candies, jellies, gummy treats, slushies, and ice cream. Discover sweet delights from our Jelly Factory and cool treats from our Ice Cream Stop.',
    logo: '/logo/jelly factory.jpeg',
    backgroundImage: '/dine/Jelly Factory web.JPG',
    category: 'Desserts & Beverages',
    contact: { phone: '+971-50-501-8540' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 83, y: 98 },
  },
  {
    slug: 'jojo',
    name: 'Jojo',
    description: 'A colorful candy store offering a wide variety of bulk candies, gummies, chocolates, and sweet treats. Discover an extensive selection of candies in a playful, vibrant setting with a gumball machine and delightful candy displays.',
    logo: '/logo/JojoLogo.png',
    backgroundImage: '/dine/jojo web.JPG',
    category: 'Desserts & Beverages',
    contact: { phone: '+971-50-501-8541' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 84, y: 99 },
  },
  {
    slug: 'juices-land',
    name: 'Juices Land',
    description: 'A tropical-themed juice bar offering fresh fruit juices, bubble tea, milk tea, and healthy beverages. Enjoy a wide selection of fresh juices made from pomegranates, oranges, apples, and more, along with a Jeely Factory candy section.',
    logo: '/logo/JuicesIslandLogo.png',
    backgroundImage: '/dine/juices land web.JPG',
    category: 'Desserts & Beverages',
    contact: { phone: '+971-50-501-8542' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 85, y: 100 },
  },
  {
    slug: 'pepes-piri-piri',
    name: 'Pepe\'s Piri Piri',
    description: 'A fast-food restaurant specializing in Piri Piri chicken, offering flame-grilled chicken, wings, wraps, burgers, and combo deals. Enjoy delicious Texan wraps, family platters, and happy hour specials with flavorful Piri Piri seasoning.',
    logo: '/logo/PepesPiriPiriLogo.png',
    backgroundImage: '/dine/pepes piri web.JPG',
    category: 'Fast Food',
    contact: { phone: '+971-50-501-8543' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 86, y: 101 },
  },
  {
    slug: 'pita',
    name: 'PITA',
    description: 'The Shawarma Revolution! A modern food stall specializing in authentic shawarmas, rice bowls, pita boxes, and Middle Eastern cuisine. Discover fresh, flavorful wraps and combos with premium ingredients, perfect for a quick and satisfying meal.',
    logo: '/logo/PitaLogo.png',
    backgroundImage: '/dine/pita web.JPG',
    category: 'Fast Food',
    contact: { phone: '+971-50-501-8544' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 87, y: 102 },
  },
  {
    slug: 'pizza-n-pasta',
    name: 'Pizza n Pasta',
    description: 'A fast-food restaurant offering delicious pizzas, pasta, burgers, subs, and salads. Enjoy XL pizzas, crunch burgers, zinger burgers, sub sandwiches, and combo deals. Perfect for families and groups with winter specials and party deals.',
    logo: '/logo/pizzanpastalogo.png',
    backgroundImage: '/dine/pizza n pasta web.JPG',
    category: 'Fast Food',
    contact: { phone: '+971-50-501-8545' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 88, y: 103 },
  },
  {
    slug: 'potato-factory',
    name: 'The Potato Factory',
    description: 'A specialty snack stall offering delicious fries in various styles. Enjoy original fries, twister fries, and other potato specialties served fresh and crispy. Perfect for a quick snack or side dish.',
    logo: '',
    backgroundImage: '/dine/potato factory web.JPG',
    category: 'Fast Food',
    contact: { phone: '+971-50-501-8546' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 89, y: 104 },
  },
  {
    slug: 'sip-smart',
    name: 'Sip Smart',
    description: 'A vibrant food stall specializing in Indian street food and fresh beverages. Enjoy authentic chaat items like Pani Puri, Gol Gappay, Dahi Bhallay, Chana Chat, Rajkachori, and Fruit Chat, along with fresh fruit juices and slushies made from fresh ingredients.',
    logo: '/logo/SipsSmartLogo.png',
    backgroundImage: '/shops/sip smart web.JPG',
    category: 'Fast Food',
    contact: { phone: '+971-50-501-8547' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 90, y: 105 },
  },
  {
    slug: 'sohaibs-wood-cocoa',
    name: 'Sohaib\'s Wood & Cocoa',
    description: 'A cozy cafe and art studio offering premium coffee, beverages, and custom wood burning portraits. Enjoy coffee served with a smile, live pyrography demonstrations, coffee tasting experiences, and unique handcrafted wood-burned artwork. A perfect blend of art and coffee culture.',
    logo: '/logo/ShoiabsWoodnCocoaLogo.png',
    backgroundImage: '/shops/sohaibs web.JPG',
    category: 'Cafe',
    contact: { phone: '+971-50-501-8548' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 91, y: 106 },
  },
  {
    slug: 'tawa-chatkhara',
    name: 'Tawa Chatkhara',
    description: 'A vibrant food stall specializing in tawa-cooked dishes and flavorful street food. Enjoy freshly prepared meals cooked on traditional flat griddles, featuring a variety of delicious options with bold flavors and authentic taste.',
    logo: '/logo/TawaChatkharaLogo.png',
    backgroundImage: '/dine/tawa chatkhara web.JPG',
    category: 'Fast Food',
    contact: { phone: '+971-50-501-8549' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 92, y: 107 },
  },
  {
    slug: 'tayto',
    name: 'Tayto',
    description: 'A modern cafe and restaurant offering a diverse menu of burgers, pasta, fish & chips, steaks, coffee, and desserts. Enjoy smash burgers, signature grilled chicken, herb olive beef steak, and combo deals. Perfect for dine-in or take-away with a slogan "lovin\' good food".',
    logo: '/logo/TaytoLogo.png',
    backgroundImage: '/dine/tayto web.JPG',
    category: 'Restaurant',
    contact: { phone: '+971-50-501-8550' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 93, y: 108 },
  },
  {
    slug: 'turk-station',
    name: 'Turk Station',
    description: 'We don\'t sell ice cream, we sell happiness! A dessert kiosk specializing in Turkish-style ice cream, rolled ice cream, and frozen treats. Enjoy premium ice cream served with a smile, featuring traditional Turkish ice cream preparation and a variety of delicious flavors.',
    logo: '/logo/TurkStationLogo.png',
    backgroundImage: '/dine/turk web.JPG',
    category: 'Desserts & Beverages',
    contact: { phone: '+971-50-501-8552' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 94, y: 109 },
  },
  {
    slug: 'true-taste',
    name: 'True Taste',
    description: 'A vibrant food stall offering a wide array of snacks and beverages. Enjoy steamed, fried, and cheese momos, various bubble teas and boba, traditional chai, hearty lasagna, refreshing sodas, coffees, falooda, and ice cream shakes. Perfect for a quick and satisfying meal.',
    logo: '/logo/TrueTasteLogo.png',
    backgroundImage: '/dine/true tast web.JPG',
    category: 'Fast Food',
    contact: { phone: '+971-50-501-8553' },
    floor: floorsMap['Ground Floor'],
    floorId: floorsMap['Ground Floor']?.id,
    mapPosition: { x: 96, y: 111 },
  },
  
  ]
  ;

  const existing = await dineRepository.findOne({
    where: { slug: sampleDine[0].slug! },
  });

  if (!existing) {
    for (const dine of sampleDine) {
      const dineEntity = dineRepository.create(dine);
      await dineRepository.save(dine);
      console.log(`Created dine: ${dine.name}`);
    }
  } else {
    console.log(`Dine ${sampleDine[0].slug} already exists`);
  }
}

